/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as SUsernameDesignSlugRouteImport } from './routes/s.$username.$designSlug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const SUsernameDesignSlugRoute = SUsernameDesignSlugRouteImport.update({
  id: '/s/$username/$designSlug',
  path: '/s/$username/$designSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/publish'
    | '/studio'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/s/$username/$designSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/publish'
    | '/studio'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/s/$username/$designSlug'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/login'
    | '/publish'
    | '/studio'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/s/$username/$designSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublishRoute: typeof PublishRoute
  StudioRoute: typeof StudioRoute
  UUsernameRoute: typeof UUsernameRoute
  SUsernameDesignSlugRoute: typeof SUsernameDesignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/s/$username/$designSlug': {
      id: '/s/$username/$designSlug'
      path: '/s/$username/$designSlug'
      fullPath: '/s/$username/$designSlug'
      preLoaderRoute: typeof SUsernameDesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsCliRoute: typeof DocsCliRoute
  DocsFaqRoute: typeof DocsFaqRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCliRoute: DocsCliRoute,
  DocsFaqRoute: DocsFaqRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PublishRoute: PublishRoute,
  StudioRoute: StudioRoute,
  UUsernameRoute: UUsernameRoute,
  SUsernameDesignSlugRoute: SUsernameDesignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
