/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminDesignsRouteImport } from './routes/admin.designs'
import { Route as SUsernameDesignSlugRouteImport } from './routes/s.$username.$designSlug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignsRoute = AdminDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AdminRoute,
} as any)
const SUsernameDesignSlugRoute = SUsernameDesignSlugRouteImport.update({
  id: '/s/$username/$designSlug',
  path: '/s/$username/$designSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/publish': typeof PublishRoute
  '/studio': typeof StudioRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/s/$username/$designSlug': typeof SUsernameDesignSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/bookmarks'
    | '/docs'
    | '/login'
    | '/publish'
    | '/studio'
    | '/admin/designs'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/users'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/admin/'
    | '/docs/'
    | '/s/$username/$designSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bookmarks'
    | '/login'
    | '/publish'
    | '/studio'
    | '/admin/designs'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/users'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/admin'
    | '/docs'
    | '/s/$username/$designSlug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/bookmarks'
    | '/docs'
    | '/login'
    | '/publish'
    | '/studio'
    | '/admin/designs'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/users'
    | '/docs/cli'
    | '/docs/faq'
    | '/u/$username'
    | '/admin/'
    | '/docs/'
    | '/s/$username/$designSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublishRoute: typeof PublishRoute
  StudioRoute: typeof StudioRoute
  UUsernameRoute: typeof UUsernameRoute
  SUsernameDesignSlugRoute: typeof SUsernameDesignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/designs': {
      id: '/admin/designs'
      path: '/designs'
      fullPath: '/admin/designs'
      preLoaderRoute: typeof AdminDesignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$username/$designSlug': {
      id: '/s/$username/$designSlug'
      path: '/s/$username/$designSlug'
      fullPath: '/s/$username/$designSlug'
      preLoaderRoute: typeof SUsernameDesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDesignsRoute: typeof AdminDesignsRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDesignsRoute: AdminDesignsRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsCliRoute: typeof DocsCliRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCliRoute: DocsCliRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PublishRoute: PublishRoute,
  StudioRoute: StudioRoute,
  UUsernameRoute: UUsernameRoute,
  SUsernameDesignSlugRoute: SUsernameDesignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
